apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: udaconnect-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-app
  template:
    metadata:
      labels:
        service: udaconnect-app
    spec:
      containers:
      - image: udaconnect-app:1.0.0
        name: udaconnect-app
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1024Mi"
            cpu: "512m"
          limits:
            memory: "1536Mi"
            cpu: "1024m"
      restartPolicy: Always
